Add Avail Wallet
MetaMask/snaps-registry pull request #706
Opened 2024-07-19 14:30 UTC by Montoya

This closes #705

This is planned to be merged next week (ideally Monday)

2024-07-29 08:31 UTC, FrederikBolding requested changes
The Snap should not be logging objects that contain potentially sensitive information.

2024-07-31 19:19 UTC, Montoya commented
@FrederikBolding the logging statements have been removed, can be confirmed on npm: https://www.npmjs.com/package/@avail-project/avail-snap?activeTab=code

Ready for re-review

2024-07-31 20:03 UTC, FrederikBolding submitted a review, later dismissed

2024-08-01 08:42 UTC, FrederikBolding approved these changes

2024-08-01 08:45 UTC, GuillaumeRx approved these changes

2024-08-01 08:45 UTC, david0xd approved these changes

2024-08-01 08:45 UTC, merged