New kobosu
MetaMask/snaps-registry pull request #908
Opened 2024-10-24 13:52 UTC by khanti42

2024-11-15 10:35 UTC, Montoya requested changes

2024-11-15 10:35 UTC, Montoya commented on src/registry.json
> +        "summary": "Trade and manage dogecoin, DRC-20, Dunes, and Doginals and more",
Dunes, ~~and~~ Doginals and more

2024-11-15 10:47 UTC, Montoya approved these changes

2024-11-19 01:54 UTC, Montoya approved these changes

2024-11-19 13:59 UTC, FrederikBolding approved these changes

2024-11-19 13:59 UTC, merged