New Stellar wallet
MetaMask/snaps-registry pull request #948
Opened 2024-11-25 12:17 UTC by khanti42

2025-01-06 15:13 UTC, khanti42 commented
@Montoya, the builder mentioned some screenshots you wanted to update. Would you like to include them here now, or should we plan for a follow-up update? The builder also wants to update the URL to the production version later, so we could align the screenshot updates with that change if it works for you. Wdyt ?

2025-01-07 22:54 UTC, Montoya commented
I don't recall anything about updating screenshots @khanti42

2025-01-07 23:08 UTC, Montoya commented
The Snap codebase is full of console.log statements that include user / state metadata. All of these console log messages need to be removed.

2025-01-07 23:09 UTC, Montoya requested changes
The Snap codebase is full of console.log statements that include user / state metadata. All of these console log messages need to be removed.

2025-04-22 15:31 UTC, Montoya commented
Closing for now until we hear back from the team on launch plans

2025-04-22 15:31 UTC, closed without merging