New EOS Wallet
MetaMask/snaps-registry pull request #949
Opened 2024-11-25 12:34 UTC by khanti42

2024-12-03 14:28 UTC, Montoya approved these changes

2024-12-03 15:08 UTC, mario-christopher submitted a review, later dismissed

2024-12-05 07:35 UTC, khanti42 commented
Please hold off on merging for now. Here’s the update the builder is currently working on:

They are updating the Snap to change how index numbers are used during key derivation. The update won’t impact MetaMask’s security model or functionality, but it will enhance EOS account security and permissions by:
- Using the derived key from index 0 as the “owner” key of the account.
- Reserving index ≥ 1 for the “active” key or any additional permissions the user adds.
- Restricting signing transactions to keys with index ≥ 1, leaving the index 0 key as a potential account recovery path for users.

This adjustment sets up the Snap and users for future features that leverage EOS’s unique account and permission structures.


cc: @mario-christopher , @Montoya

2024-12-05 10:06 UTC, FrederikBolding requested changes
Blocking based on @khanti42s comment above

2024-12-09 15:46 UTC, khanti42 commented
Unblocking. Builder pushed the required fixes and are ready for allowlisting. 

Message Received From builder: 


> Alright, these changes are now complete and we’ve published a 1.1.0 version of the Snap. Creation via the updated page at the URL below has been tested and all seems to be working as intended!
>   https://unicove.com/en/eos/metamask
>
> The one thing this is going to do is prevent previously created accounts from logging in, due to the indexes changing. That’s why they wanted to get it published before any real users started using the snap. Considering only our two teams have ever used this system, this shouldn’t be an issue and no real users are affected. 

For testing purposes, everyone will need to establish new accounts. Account creation system has been reset to allow all already registered social logins to claim free accounts.

2024-12-09 15:54 UTC, Montoya approved these changes

2024-12-09 20:46 UTC, mario-christopher approved these changes

2024-12-12 17:19 UTC, merged